config/dtb: nokia-nd1: Add panel drivers
msm89x7-mainline/linux-panel-drivers pull request #3
Opened 2024-11-23 04:25 UTC by andrewgigena

Ready to merge.

2025-01-09 10:45 UTC, andrewgigena commented
@barni2000 I rebased and pushed the changes. I see a traceback when running `generate.sh` but all the device's panels are being captured before the crash, so it's not a big deal.

```
======== nokia-nd1.sh ========
Parsing: /disks/postmarketos/repos/postmarketos/linux-panel-drivers/dtb/nokia-nd1.dtb
Parsing: sim_video (Simulator video mode dsi panel)
Generating: sim_video (Simulator video mode dsi panel)
Parsing: sim_cmd (Simulator cmd mode dsi panel)
Generating: sim_cmd (Simulator cmd mode dsi panel)
Parsing: truly_1080p_video (truly 1080p video mode dsi panel)
Generating: truly_1080p_video (truly 1080p video mode dsi panel)
Parsing: truly_1080p_cmd (truly 1080p cmd mode dsi panel)
Generating: truly_1080p_cmd (truly 1080p cmd mode dsi panel)
Parsing: r69006_1080p_cmd (r69006 1080p cmd mode dsi panel)
Generating: r69006_1080p_cmd (r69006 1080p cmd mode dsi panel)
Parsing: r69006_1080p_video (r69006 1080p video mode dsi panel)
Generating: r69006_1080p_video (r69006 1080p video mode dsi panel)
Parsing: hx8394f_720p_video (hx8394f 720p video mode dsi panel)
Generating: hx8394f_720p_video (hx8394f 720p video mode dsi panel)
Parsing: adv7533_1080p (dsi_adv7533_1080p)
Generating: adv7533_1080p (dsi_adv7533_1080p)
Parsing: adv7533_720p (dsi_adv7533_720p)
Generating: adv7533_720p (dsi_adv7533_720p)
Parsing: truly_720p_video (truly 720p video mode dsi panel)
Generating: truly_720p_video (truly 720p video mode dsi panel)
Parsing: truly_wuxga_video (truly wuxga video mode dsi panel)
Generating: truly_wuxga_video (truly wuxga video mode dsi panel)
Parsing: truly_720p_cmd (truly 720p cmd mode dsi panel)
Generating: truly_720p_cmd (truly 720p cmd mode dsi panel)
Parsing: lead_fl10802_fwvga_video (lead fl10802 fwvga video mode dsi panel)
Generating: lead_fl10802_fwvga_video (lead fl10802 fwvga video mode dsi panel)
Parsing: icn9706_720_1440p_video (icn9706 720 1440p video mode dsi panel)
Generating: icn9706_720_1440p_video (icn9706 720 1440p video mode dsi panel)
WARNING: DCS command SOFT_RESET with incorrect argument count (expected: 0, is: 1). Consider using --dumb-dcs
Parsing: r61322_1080p_video (r61322 1080p video mode dsi panel)
Generating: r61322_1080p_video (r61322 1080p video mode dsi panel)
Parsing: mdss_dsi_ili7807e_1080p_video (ili7807e 1080p video mode dsi panel)
Generating: mdss_dsi_ili7807e_1080p_video (ili7807e 1080p video mode dsi panel)
WARNING: DCS command ENTER_IDLE_MODE with incorrect argument count (expected: 0, is: 1). Consider using --dumb-dcs
Parsing: mdss_dsi_hx8394a_720p_video (hx8394a 720p video mode dsi panel)
Generating: mdss_dsi_hx8394a_720p_video (hx8394a 720p video mode dsi panel)
Parsing: mdss_dsi_nt35521_720p_video (nt35521 720p video mode dsi panel)
Generating: mdss_dsi_nt35521_720p_video (nt35521 720p video mode dsi panel)
Parsing: mdss_dsi_nt35521s_720p_video (nt35521s 720p video mode dsi panel)
Generating: mdss_dsi_nt35521s_720p_video (nt35521s 720p video mode dsi panel)
Parsing: mdss_dsi_pj050ia_nt35521s_720p_video (PA050IA nt35521s 720p video mode dsi panel)
Generating: mdss_dsi_pj050ia_nt35521s_720p_video (PA050IA nt35521s 720p video mode dsi panel)
Parsing: sharp_ft8607_720p_video (OC6 SHARP ft8607 720p video mode dsi panel)
Generating: sharp_ft8607_720p_video (OC6 SHARP ft8607 720p video mode dsi panel)
Traceback (most recent call last):
  File "/disks/postmarketos/repos/postmarketos/linux-panel-drivers/linux-mdss-dsi-panel-driver-generator/lmdpdg.py", line 79, in <module>
    generate(panel, args)
  File "/disks/postmarketos/repos/postmarketos/linux-panel-drivers/linux-mdss-dsi-panel-driver-generator/lmdpdg.py", line 31, in generate
    generate_lk_driver(p)
  File "/disks/postmarketos/repos/postmarketos/linux-panel-drivers/linux-mdss-dsi-panel-driver-generator/lk.py", line 158, in generate_lk_driver
    {generate_commands(p, 'on')}
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disks/postmarketos/repos/postmarketos/linux-panel-drivers/linux-mdss-dsi-panel-driver-generator/lk.py", line 24, in generate_commands
    assert len(c.payload) <= 2, f"Payload too long: {len(c.payload)}"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: Payload too long: 3
```

2025-01-09 22:46 UTC, barni2000 commented
you can decompile and recompile your dt with dtc to remove sharp_ft8607_720p_video

2025-01-09 22:47 UTC, barni2000 requested changes

2025-01-09 22:47 UTC, barni2000 commented on config/nokia-nd1.sh
> +	[mdss_dsi_pj050ia_nt35521s_720p_video]="nokia,nd1-pj050ia_nt35521s"
```suggestion
	[mdss_dsi_pj050ia_nt35521s_720p_video]="nokia,nd1-nt35521s-pj050ia"
```

2025-07-16 10:52 UTC, merged

2025-07-16 10:52 UTC, barni2000 commented
Thanks!